name = "MakieExtra"
uuid = "54e234d5-9986-40d8-815f-a5e42de435f6"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.6"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PyFormattedStrings = "5f89f4a4-a228-4886-b223-c468a82ed5b9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Accessors = "0.1.36"
InverseFunctions = "0.1.14"
Makie = "0.20.9, 0.21"
PyFormattedStrings = "0.1"
Reexport = "1.2.2"
julia = "1.9"
