name = "MakieExtra"
uuid = "54e234d5-9986-40d8-815f-a5e42de435f6"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.48"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
DataManipulation = "38052440-ad76-4236-8414-61389b2c5143"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
KwdefHelpers = "80d9ef48-13f8-4f87-9333-d4c97b041895"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ObjectiveC = "e86c9b32-1129-44ac-8ea0-90d5bb39ded9"
PyFormattedStrings = "5f89f4a4-a228-4886-b223-c468a82ed5b9"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructHelpers = "4093c41a-2008-41fd-82b8-e3f9d02b504f"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
GLMakieExt = "GLMakie"

[compat]
AccessorsExtra = "0.1"
DataManipulation = "0.1"
DataPipes = "0.3"
GLMakie = "0.10"
InverseFunctions = "0.1"
KwdefHelpers = "0.1"
Makie = "0.21, 0.22"
ObjectiveC = "3"
PyFormattedStrings = "0.1"
Reexport = "1.2"
StructHelpers = "1"
julia = "1.9"
